spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wangtao
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t9MuESzmq62wZSWtd4r
    access-key-secret: 8jTwwXD3XgrWWNThQpqMQkmMUuRgnV
    bucket-name: web-wtwt
